//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.02.10 at 10:15:20 PM CET
//


package com.topografix.gpx._private.topografix._0._4;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import com.topografix.gpx._1._1.PtType;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.topografix.gpx._private.topografix._0._4 package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PointSymbol_QNAME = new QName("http://www.topografix.com/GPX/Private/TopoGrafix/0/4", "point_symbol");
    private final static QName _UseDocStyle_QNAME = new QName("http://www.topografix.com/GPX/Private/TopoGrafix/0/4", "use_doc_style");
    private final static QName _BaseUrl_QNAME = new QName("http://www.topografix.com/GPX/Private/TopoGrafix/0/4", "base_url");
    private final static QName _SelectionPt_QNAME = new QName("http://www.topografix.com/GPX/Private/TopoGrafix/0/4", "selection_pt");
    private final static QName _ActivePoint_QNAME = new QName("http://www.topografix.com/GPX/Private/TopoGrafix/0/4", "active_point");
    private final static QName _Cased_QNAME = new QName("http://www.topografix.com/GPX/Private/TopoGrafix/0/4", "cased");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.topografix.gpx._private.topografix._0._4
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SelectionRange }
     *
     */
    public SelectionRange createSelectionRange() {
        return new SelectionRange();
    }

    /**
     * Create an instance of {@link Marker }
     *
     */
    public Marker createMarker() {
        return new Marker();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.topografix.com/GPX/Private/TopoGrafix/0/4", name = "point_symbol")
    public JAXBElement<String> createPointSymbol(String value) {
        return new JAXBElement<String>(_PointSymbol_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.topografix.com/GPX/Private/TopoGrafix/0/4", name = "use_doc_style")
    public JAXBElement<Boolean> createUseDocStyle(Boolean value) {
        return new JAXBElement<Boolean>(_UseDocStyle_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.topografix.com/GPX/Private/TopoGrafix/0/4", name = "base_url")
    public JAXBElement<String> createBaseUrl(String value) {
        return new JAXBElement<String>(_BaseUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PtType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.topografix.com/GPX/Private/TopoGrafix/0/4", name = "selection_pt")
    public JAXBElement<PtType> createSelectionPt(PtType value) {
        return new JAXBElement<PtType>(_SelectionPt_QNAME, PtType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PtType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.topografix.com/GPX/Private/TopoGrafix/0/4", name = "active_point")
    public JAXBElement<PtType> createActivePoint(PtType value) {
        return new JAXBElement<PtType>(_ActivePoint_QNAME, PtType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.topografix.com/GPX/Private/TopoGrafix/0/4", name = "cased")
    public JAXBElement<Boolean> createCased(Boolean value) {
        return new JAXBElement<Boolean>(_Cased_QNAME, Boolean.class, null, value);
    }

}
