//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.02.10 at 10:15:20 PM CET
//


package com.topografix.gpx._private.topografix._0._4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.topografix.gpx._1._1.PtType;


/**
 *
 *   Two points defining the start and end of a selection (on a linear feature like rte or trk)
 *
 *
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pt_start" type="{http://www.topografix.com/GPX/1/1}ptType"/>
 *         &lt;element name="pt_end" type="{http://www.topografix.com/GPX/1/1}ptType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ptStart",
    "ptEnd"
})
@XmlRootElement(name = "selection_range")
public class SelectionRange {

    @XmlElement(name = "pt_start", required = true)
    protected PtType ptStart;
    @XmlElement(name = "pt_end", required = true)
    protected PtType ptEnd;

    /**
     * Gets the value of the ptStart property.
     *
     * @return
     *     possible object is
     *     {@link PtType }
     *
     */
    public PtType getPtStart() {
        return ptStart;
    }

    /**
     * Sets the value of the ptStart property.
     *
     * @param value
     *     allowed object is
     *     {@link PtType }
     *
     */
    public void setPtStart(PtType value) {
        this.ptStart = value;
    }

    /**
     * Gets the value of the ptEnd property.
     *
     * @return
     *     possible object is
     *     {@link PtType }
     *
     */
    public PtType getPtEnd() {
        return ptEnd;
    }

    /**
     * Sets the value of the ptEnd property.
     *
     * @param value
     *     allowed object is
     *     {@link PtType }
     *
     */
    public void setPtEnd(PtType value) {
        this.ptEnd = value;
    }

}
