//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.02 at 04:06:17 PM CET 
//


package com.topografix.gpx.gpx_style._0._2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for genericFontFamilyType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="genericFontFamilyType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="serif"/>
 *     &lt;enumeration value="sans-serif"/>
 *     &lt;enumeration value="cursive"/>
 *     &lt;enumeration value="fantasy"/>
 *     &lt;enumeration value="monospace"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "genericFontFamilyType")
@XmlEnum
public enum GenericFontFamilyType {

    @XmlEnumValue("serif")
    SERIF("serif"),
    @XmlEnumValue("sans-serif")
    SANS_SERIF("sans-serif"),
    @XmlEnumValue("cursive")
    CURSIVE("cursive"),
    @XmlEnumValue("fantasy")
    FANTASY("fantasy"),
    @XmlEnumValue("monospace")
    MONOSPACE("monospace");
    private final String value;

    GenericFontFamilyType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GenericFontFamilyType fromValue(String v) {
        for (GenericFontFamilyType c: GenericFontFamilyType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
