//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.02 at 04:06:17 PM CET 
//


package com.topografix.gpx.gpx_overlay._0._3;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.topografix.gpx.gpx_style._0._2.FillType;
import com.topografix.gpx.gpx_style._0._2.LineType;
import com.topografix.gpx.gpx_style._0._2.TextType;


/**
 * 
 * 		Text overlay (waypoint or route map label, e.g.)
 * 	  
 * 
 * <p>Java class for labelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="labelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="point" type="{http://www.topografix.com/GPX/gpx_overlay/0/3}ptType" minOccurs="0"/>
 *           &lt;element name="translate" type="{http://www.topografix.com/GPX/gpx_overlay/0/3}xyOffsetType" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="rotate" type="{http://www.topografix.com/GPX/gpx_overlay/0/3}degreesType" minOccurs="0"/>
 *         &lt;element name="margin" type="{http://www.topografix.com/GPX/gpx_overlay/0/3}xyOffsetType" minOccurs="0"/>
 *         &lt;element name="label_text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="derived_from" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www.topografix.com/GPX/gpx_overlay/0/3}max_scale" minOccurs="0"/>
 *         &lt;element ref="{http://www.topografix.com/GPX/gpx_style/0/2}text" minOccurs="0"/>
 *         &lt;element ref="{http://www.topografix.com/GPX/gpx_style/0/2}line" minOccurs="0"/>
 *         &lt;element ref="{http://www.topografix.com/GPX/gpx_style/0/2}fill" minOccurs="0"/>
 *         &lt;element name="extensions" type="{http://www.topografix.com/GPX/gpx_overlay/0/3}extensionsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "labelType", propOrder = {
    "point",
    "translate",
    "rotate",
    "margin",
    "labelText",
    "derivedFrom",
    "type",
    "maxScale",
    "text",
    "line",
    "fill",
    "extensions"
})
public class LabelType {

    protected PtType point;
    protected XyOffsetType translate;
    protected BigDecimal rotate;
    protected XyOffsetType margin;
    @XmlElement(name = "label_text")
    protected String labelText;
    @XmlElement(name = "derived_from")
    protected String derivedFrom;
    protected String type;
    @XmlElement(name = "max_scale")
    protected BigDecimal maxScale;
    @XmlElement(namespace = "http://www.topografix.com/GPX/gpx_style/0/2")
    protected TextType text;
    @XmlElement(namespace = "http://www.topografix.com/GPX/gpx_style/0/2")
    protected LineType line;
    @XmlElement(namespace = "http://www.topografix.com/GPX/gpx_style/0/2")
    protected FillType fill;
    protected ExtensionsType extensions;

    /**
     * Gets the value of the point property.
     * 
     * @return
     *     possible object is
     *     {@link PtType }
     *     
     */
    public PtType getPoint() {
        return point;
    }

    /**
     * Sets the value of the point property.
     * 
     * @param value
     *     allowed object is
     *     {@link PtType }
     *     
     */
    public void setPoint(PtType value) {
        this.point = value;
    }

    /**
     * Gets the value of the translate property.
     * 
     * @return
     *     possible object is
     *     {@link XyOffsetType }
     *     
     */
    public XyOffsetType getTranslate() {
        return translate;
    }

    /**
     * Sets the value of the translate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XyOffsetType }
     *     
     */
    public void setTranslate(XyOffsetType value) {
        this.translate = value;
    }

    /**
     * Gets the value of the rotate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRotate() {
        return rotate;
    }

    /**
     * Sets the value of the rotate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRotate(BigDecimal value) {
        this.rotate = value;
    }

    /**
     * Gets the value of the margin property.
     * 
     * @return
     *     possible object is
     *     {@link XyOffsetType }
     *     
     */
    public XyOffsetType getMargin() {
        return margin;
    }

    /**
     * Sets the value of the margin property.
     * 
     * @param value
     *     allowed object is
     *     {@link XyOffsetType }
     *     
     */
    public void setMargin(XyOffsetType value) {
        this.margin = value;
    }

    /**
     * Gets the value of the labelText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelText() {
        return labelText;
    }

    /**
     * Sets the value of the labelText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelText(String value) {
        this.labelText = value;
    }

    /**
     * Gets the value of the derivedFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDerivedFrom() {
        return derivedFrom;
    }

    /**
     * Sets the value of the derivedFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDerivedFrom(String value) {
        this.derivedFrom = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * 
     * 			 Maximum scale at which the parent object is displayed on a map.  "24000" for a 1:24000 scale USGS topo, e.g.
     * 		   
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxScale() {
        return maxScale;
    }

    /**
     * Sets the value of the maxScale property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxScale(BigDecimal value) {
        this.maxScale = value;
    }

    /**
     * 
     * 	  	   Text styling hints for the text overlay
     * 	      
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setText(TextType value) {
        this.text = value;
    }

    /**
     * 
     * 	  	   styling hints for bounding box of the the text overlay
     * 	      
     * 
     * @return
     *     possible object is
     *     {@link LineType }
     *     
     */
    public LineType getLine() {
        return line;
    }

    /**
     * Sets the value of the line property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineType }
     *     
     */
    public void setLine(LineType value) {
        this.line = value;
    }

    /**
     * 
     * 	  	   styling hints for the background of the bounding box of the text overlay
     * 	      
     * 
     * @return
     *     possible object is
     *     {@link FillType }
     *     
     */
    public FillType getFill() {
        return fill;
    }

    /**
     * Sets the value of the fill property.
     * 
     * @param value
     *     allowed object is
     *     {@link FillType }
     *     
     */
    public void setFill(FillType value) {
        this.fill = value;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionsType }
     *     
     */
    public ExtensionsType getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionsType }
     *     
     */
    public void setExtensions(ExtensionsType value) {
        this.extensions = value;
    }

}
