//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.02 at 04:06:17 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.topografix.com/GPX/gpx_overlay/0/3", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.topografix.gpx.gpx_overlay._0._3;
