//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.02 at 04:06:17 PM CET 
//


package com.topografix.gpx.gpx_overlay._0._3;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.topografix.gpx.gpx_style._0._2.FillType;
import com.topografix.gpx.gpx_style._0._2.LineType;


/**
 * 
 * 		polyline represents an ordered list of points describing a closed or open shape.
 * 	  
 * 
 * <p>Java class for polylineType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="polylineType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www.topografix.com/GPX/gpx_overlay/0/3}max_scale" minOccurs="0"/>
 *         &lt;element ref="{http://www.topografix.com/GPX/gpx_overlay/0/3}label" minOccurs="0"/>
 *         &lt;element ref="{http://www.topografix.com/GPX/gpx_style/0/2}line" minOccurs="0"/>
 *         &lt;element ref="{http://www.topografix.com/GPX/gpx_style/0/2}fill" minOccurs="0"/>
 *         &lt;element name="extensions" type="{http://www.topografix.com/GPX/gpx_overlay/0/3}extensionsType" minOccurs="0"/>
 *         &lt;element name="points" type="{http://www.topografix.com/GPX/gpx_overlay/0/3}pointsType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "polylineType", propOrder = {
    "desc",
    "type",
    "maxScale",
    "label",
    "line",
    "fill",
    "extensions",
    "points"
})
public class PolylineType {

    protected String desc;
    protected String type;
    @XmlElement(name = "max_scale")
    protected BigDecimal maxScale;
    protected LabelType label;
    @XmlElement(namespace = "http://www.topografix.com/GPX/gpx_style/0/2")
    protected LineType line;
    @XmlElement(namespace = "http://www.topografix.com/GPX/gpx_style/0/2")
    protected FillType fill;
    protected ExtensionsType extensions;
    protected List<PointsType> points;

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc(String value) {
        this.desc = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * 
     * 			 Maximum scale at which the parent object is displayed on a map.  "24000" for a 1:24000 scale USGS topo, e.g.
     * 		   
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxScale() {
        return maxScale;
    }

    /**
     * Sets the value of the maxScale property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxScale(BigDecimal value) {
        this.maxScale = value;
    }

    /**
     * 
     * 			Map label for polyline
     * 		   
     * 
     * @return
     *     possible object is
     *     {@link LabelType }
     *     
     */
    public LabelType getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelType }
     *     
     */
    public void setLabel(LabelType value) {
        this.label = value;
    }

    /**
     * 
     * 	  	   polyline line style
     * 	      
     * 
     * @return
     *     possible object is
     *     {@link LineType }
     *     
     */
    public LineType getLine() {
        return line;
    }

    /**
     * Sets the value of the line property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineType }
     *     
     */
    public void setLine(LineType value) {
        this.line = value;
    }

    /**
     * 
     * 	  	   polyline fill style
     * 	      
     * 
     * @return
     *     possible object is
     *     {@link FillType }
     *     
     */
    public FillType getFill() {
        return fill;
    }

    /**
     * Sets the value of the fill property.
     * 
     * @param value
     *     allowed object is
     *     {@link FillType }
     *     
     */
    public void setFill(FillType value) {
        this.fill = value;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionsType }
     *     
     */
    public ExtensionsType getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionsType }
     *     
     */
    public void setExtensions(ExtensionsType value) {
        this.extensions = value;
    }

    /**
     * Gets the value of the points property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the points property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPoints().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PointsType }
     * 
     * 
     */
    public List<PointsType> getPoints() {
        if (points == null) {
            points = new ArrayList<PointsType>();
        }
        return this.points;
    }

}
